version: '3'
services:

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis_container
    ports:
      - "6379:6379"